name: Test project

on: push

jobs:
  testE2E:
    name: Test E2E
    runs-on: [self-hosted, Windows]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: RunAppAndTests
        run: |
          ./2d-game/2d-game/build/LightSouls.exe
          D:\Programs\Unity\2021.3.10f1\Editor\Unity -projectPath /2d-game/2d-game -executeMethod Altom.AltTesterEditor.AltTestRunner.RunTestFromCommandLine -testsClass EndToEnd -reportPath testReport.xml -logFile logFile.log -batchmode -quit
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Report 
          path: testReport.xml